xbmc/kodi-tv

package-lock.json
package.json
src/components/Button.tsx
src/components/HeaderMenu.tsx
src/components/Social.tsx

Not sure how happy we will be with the icons, but they work and should be easily replaceable. It's kind of a pita to have rounded icons with icons in them :/

Remove outline from dropdown

---

package-lock.json
src/cms/netlify.tsx
src/components/Footer.tsx
src/components/FullWidth.tsx
src/components/SectionWidgets.tsx
src/components/SponsorList.tsx
src/hooks/Sponsors.tsx
src/pages/index.tsx

Also introduces a sponsor interface type and uses it to get rid of som cruft
Fixes https://github.com/xbmc/kodi-tv/issues/107

Add links to sponsor mentions

---

src/components/Button.tsx
src/components/Carousel.tsx
src/components/FullWidth.tsx
src/components/Hero.tsx

Also get rid of the gradient in clickable buttons, as these can't be animated

Add secondary button style and make button bigger 

---

src/components/Header.tsx
src/components/HeaderDropdownMenu.tsx
src/components/HeaderDropdownMenuMobile.tsx

Also gets rid of menuCollapse which seemed unused?

Type header

---

src/components/AddonLayout.tsx
src/components/Blog.tsx
src/components/Button.tsx
src/components/Card.tsx
src/components/Carousel.tsx
src/components/FullWidth.tsx
src/components/Header.tsx
src/components/HeaderDropdownMenu.tsx
src/components/HeaderDropdownMenuMobile.tsx
src/components/Hero.tsx
src/components/IconList.tsx
src/components/Layout.tsx
src/components/Pager.tsx
src/components/SectionWidgets.tsx
src/components/SponsorList.tsx
src/hooks/Stats.tsx
src/pages/donate/wall.tsx
src/pages/index.tsx

Slight change to the statistics subtitle color and background.
Try to not use white if possible, as it should be easier on the eyes/better design.
https://graphicdesign.stackexchange.com/a/25360

Change colors

---

package-lock.json
package.json
postcss.config.js
src/components/FullWidth.tsx
tailwind.config.js

Can't get this to work. Maybe you can @pkscout I think the css isn't created correctly.
Filters are a new feature (so it might actually be broken?) https://github.com/tailwindlabs/tailwindcss/releases/tag/v2.1.0

Add filters to sponsors

---

src/components/Header.tsx

Change irc to libera.chat

---

.github/workflows/build.yml

Add build pipeline

---

src/components/Header.tsx
src/components/HeaderDropdownMenu.tsx

This fixes the preloading of the internal links used in the header component.
Cudos to @da-anda for finding this

Fix header links

---

src/pages/index.tsx

I added a comma to the index page of the website.

added comma

---

src/components/Header.tsx

Related to doxygen changes and the now available:
- https://xbmc.github.io/docs.kodi.tv/master/kodi-base - https://docs.kodi.tv
- https://xbmc.github.io/docs.kodi.tv/master/kodi-dev-kit - https://dev-kit.kodi.tv

allow two docs one about addons one about Kodi itself

---

scripts/addon-parser/app.js

Update regex for forum thread count

---

scripts/addon-parser/app.js

This reverts commit ceed1f80e13f1e734f549d958f4153fe004d837f.

Revert "Update regex for forum thread count"

---

scripts/addon-parser/app.js

Also adds some vague typing
Closes #648

Fix CR not being replaced in some cases

---

scripts/addon-parser/app.js

This will hopefully help with diffs, as it keeps the top layer consistent
So only a change for better maintainability

Sort json file content

---

package-lock.json
package.json

Revert "Bump decap-cms-app from 3.0.12 to 3.1.2"

---

src/components/Footer.tsx

Align text with url

---

src/components/Footer.tsx

Add tvheadend and sort by alphabet

---

src/cms/decap.tsx
src/components/Footer.tsx
src/components/FullWidth.tsx
src/components/SectionWidgets.tsx
src/components/SponsorList.tsx
src/content/pages/donate/index.md
src/data/yaml/sponsor/flirc.yaml
src/data/yaml/sponsor/goatcounter.yaml
src/data/yaml/sponsor/leaseweb.yaml
src/data/yaml/sponsor/mac-mini-vault.yaml
src/data/yaml/sponsor/osuosl.yaml
src/data/yaml/sponsor/weblate.yaml
src/hooks/Sponsors.tsx
src/pages/index.tsx
static/admin/config.yml

Bring back sponsor levels by type

---

src/components/Footer.tsx

Add status page

---

package-lock.json
package.json
src/components/HeaderDropdownMenu.tsx

Revert "Update headless ui"
